Repository exonum/exonum, pull requests merged in 2019-11, with the labels that each got.

#1528 Document parts of Rust runtime [ECR-3285]
  exonum/src/runtime/rust/error.rs
  exonum/src/runtime/rust/mod.rs
  exonum/src/runtime/rust/service.rs
  services/supervisor/src/simple/mod.rs
  services/supervisor/tests/supervisor/config.rs
Labels: core, documentation

#1536 Add HTTP server restart params into node config [ECR-3748]
  CHANGELOG.md
  exonum/src/api/backends/actix.rs
  exonum/src/api/manager.rs
  exonum/src/events/network.rs
  exonum/src/node/mod.rs
  test-suite/testkit/src/lib.rs
Labels: core, update changelog

#1539 Restore warn(missing_docs) in the Exonum crate [ECR-3821]
  exonum/src/api/manager.rs
  exonum/src/api/mod.rs
  exonum/src/api/node/mod.rs
  exonum/src/blockchain/builder.rs
  exonum/src/blockchain/schema.rs
  exonum/src/helpers/mod.rs
  exonum/src/lib.rs
  exonum/src/node/mod.rs
  exonum/src/proto/mod.rs
  exonum/src/runtime/rust/call_context.rs
  exonum/src/runtime/rust/service.rs
  exonum/src/runtime/types.rs
Labels: core, documentation

#1538 Supervisor modes [ECR-3794] [ECR-3771]
  cli/src/lib.rs
  components/derive/src/service_dispatcher.rs
  components/derive/src/service_factory.rs
  examples/sample_runtime/src/main.rs
  services/supervisor/src/api.rs
  services/supervisor/src/errors.rs
  services/supervisor/src/lib.rs
  services/supervisor/src/mode.rs
  services/supervisor/src/proto/service.proto
  services/supervisor/src/proto_structures.rs
  services/supervisor/src/schema.rs
  services/supervisor/src/simple/api.rs
  services/supervisor/src/simple/mod.rs
  services/supervisor/src/simple/schema.rs
  services/supervisor/src/transactions.rs
  services/supervisor/tests/simple.rs
  services/supervisor/tests/supervisor/config.rs
  services/supervisor/tests/supervisor/config_api.rs
  services/supervisor/tests/supervisor/consensus_config.rs
  services/supervisor/tests/supervisor/main.rs
  services/supervisor/tests/supervisor/utils.rs
  services/time/tests/test_exonum_time.rs
Labels: supervisor, update changelog

#1544 Remove atty dependency
  exonum/Cargo.toml
Labels: core

#1540 Deploy workflow
  exonum/src/blockchain/tests.rs
  exonum/src/runtime/dispatcher/mod.rs
  exonum/src/runtime/dispatcher/tests.rs
  exonum/src/runtime/mod.rs
  exonum/src/runtime/rust/call_context.rs
  exonum/src/runtime/rust/service.rs
Labels: core, documentation

#1548 Remove TransactionMessage alias [ECR-3222]
  examples/cryptocurrency-advanced/backend/src/api.rs
  exonum/src/blockchain/mod.rs
  exonum/src/explorer/mod.rs
Labels: core

#1549 Encapsulate Blockchain fields [ECR-3222]
  exonum/src/blockchain/mod.rs
  exonum/tests/explorer/blockchain/mod.rs
  test-suite/testkit/tests/service_hooks/main.rs
Labels: core

#1547 Remove metrics module
  exonum/Cargo.toml
  exonum/src/helpers/metrics.rs
  exonum/src/helpers/mod.rs
  exonum/src/node/consensus.rs
Labels: core, update changelog

#1550 Remove isolate method [ECR-3820]
  exonum/src/runtime/rust/call_context.rs
  services/supervisor/src/lib.rs
  services/supervisor/src/transactions.rs
  services/supervisor/tests/supervisor/config.rs
  services/supervisor/tests/supervisor/inc.rs
Labels: supervisor

#1531 ProofMapIndex variants for hashed and raw keys [ECR-3777]
  CHANGELOG.md
  components/merkledb/benches/encoding.rs
  components/merkledb/src/access/extensions.rs
  components/merkledb/src/hash.rs
  components/merkledb/src/lib.rs
  components/merkledb/src/proof_map_index/key.rs
  components/merkledb/src/proof_map_index/mod.rs
  components/merkledb/src/proof_map_index/proof.rs
  components/merkledb/src/proof_map_index/proof_builder.rs
  components/merkledb/src/proof_map_index/tests.rs
  components/merkledb/src/proto/mod.rs
  components/merkledb/tests/key/mod.rs
  components/merkledb/tests/map.rs
  components/merkledb/tests/proof_map_index.rs
  examples/cryptocurrency-advanced/backend/src/api.rs
  examples/cryptocurrency-advanced/backend/src/schema.rs
  examples/timestamping/backend/src/api.rs
  examples/timestamping/backend/src/schema.rs
  exonum/src/helpers/multisig.rs
Labels: merkledb, update changelog

#1552 Assign instance IDs in the Supervisor [ECR-3746]
  exonum/src/blockchain/tests.rs
  exonum/src/runtime/dispatcher/mod.rs
  exonum/src/runtime/dispatcher/schema.rs
  exonum/src/runtime/rust/call_context.rs
  services/supervisor/src/lib.rs
  services/supervisor/src/proto_structures.rs
  services/supervisor/src/schema.rs
Labels: supervisor

#1542 Write proper examples for the Exonum traits derivation [ECR-3822]
  components/derive/src/lib.rs
  exonum/src/runtime/error.rs
  exonum/src/runtime/rust/mod.rs
  exonum/src/runtime/rust/service.rs
Labels: core, derive, documentation

#1545 Write full and meaningful description of the IndexCoordinates [ECR-3824]
  examples/cryptocurrency-advanced/backend/src/api.rs
  examples/timestamping/backend/src/api.rs
  exonum/src/blockchain/mod.rs
  exonum/src/blockchain/schema.rs
  exonum/src/runtime/dispatcher/mod.rs
  exonum/src/sandbox/consensus/basic.rs
  exonum/src/sandbox/mod.rs
Labels: core, documentation

#1560 Update changelog [ECR-3516]
  CHANGELOG.md
Labels: documentation

#1562 Implement `FromAccess` macro [ECR-3832]
  CHANGELOG.md
  components/derive/src/db_traits.rs
  components/derive/src/lib.rs
  components/merkledb/Cargo.toml
  components/merkledb/benches/schema_patterns.rs
  components/merkledb/benches/transactions.rs
  components/merkledb/examples/blockchain.rs
  components/merkledb/src/access/mod.rs
  components/merkledb/src/group.rs
  components/merkledb/tests/components.rs
  examples/cryptocurrency-advanced/backend/src/schema.rs
  examples/cryptocurrency/src/lib.rs
  examples/timestamping/backend/src/schema.rs
  services/supervisor/src/multisig.rs
  services/supervisor/src/schema.rs
  services/supervisor/tests/supervisor/inc.rs
  services/time/examples/simple_service/main.rs
  services/time/src/schema.rs
  test-suite/testkit/tests/counter/counter.rs
  test-suite/testkit/tests/inflating_currency/inflating_cryptocurrency.rs
  test-suite/testkit/tests/interfaces/schema.rs
Labels: derive, update changelog

#1571 Fix `block` bench in main crate
  .travis.yml
  exonum/benches/criterion/block.rs
Labels: work in progress :construction:

#1557 Remove max-builtin-id constant [ECR-3851]
  components/merkledb/src/db.rs
  components/merkledb/src/lib.rs
  exonum/src/runtime/dispatcher/mod.rs
  exonum/src/runtime/dispatcher/schema.rs
  services/supervisor/src/lib.rs
  services/supervisor/src/schema.rs
  services/supervisor/tests/supervisor/main.rs
Labels: core, supervisor

#1572 Restore warn(missing_docs) in testkit [ECR-3877]
  test-suite/testkit/src/api.rs
  test-suite/testkit/src/lib.rs
Labels: documentation

#1565 Improve transaction broadcast [ECR-3817]
  examples/cryptocurrency-advanced/backend/src/api.rs
  examples/cryptocurrency-advanced/backend/src/lib.rs
  examples/cryptocurrency/src/lib.rs
  examples/timestamping/backend/src/api.rs
  examples/timestamping/backend/src/lib.rs
  exonum/src/blockchain/config.rs
  exonum/src/node/mod.rs
  exonum/src/proto/schema/exonum/tests.proto
  exonum/src/runtime/api.rs
  exonum/src/runtime/mod.rs
  exonum/src/runtime/rust/api.rs
  exonum/src/runtime/rust/mod.rs
  exonum/src/runtime/rust/runtime_api.rs
  exonum/src/runtime/rust/service.rs
  exonum/src/sandbox/mod.rs
  services/supervisor/src/api.rs
  services/supervisor/src/lib.rs
  services/supervisor/tests/supervisor/inc.rs
  services/time/src/api.rs
  services/time/src/lib.rs
  test-suite/testkit/tests/counter/counter.rs
  test-suite/testkit/tests/counter/main.rs
  test-suite/testkit/tests/inflating_currency/inflating_cryptocurrency.rs
  test-suite/testkit/tests/service_hooks/hooks.rs
  test-suite/testkit/tests/service_hooks/main.rs
Labels: core

#1574 Add missing documentation for supervisor [ECR-3641]
  services/supervisor/src/lib.rs
  services/supervisor/src/schema.rs
  services/supervisor/src/transactions.rs
Labels: documentation

#1578 Explicit panic invocation in from_access
  components/merkledb/src/access/extensions.rs
  components/merkledb/src/group.rs
  components/merkledb/src/lazy.rs
Labels: merkledb

#1575 Additional tests for list proof deserialization [ECR-3752]
  components/merkledb/src/proto/mod.rs
Labels: merkledb

#1558 Harsher naming restrictions in MerkleDB APIs [ECR-3834]
  CHANGELOG.md
  components/derive/src/service_factory.rs
  components/merkledb/src/access/mod.rs
  components/merkledb/src/proof_list_index/tests.rs
  components/merkledb/src/proof_map_index/key.rs
  components/merkledb/src/proof_map_index/tests.rs
  components/merkledb/src/validation.rs
  components/merkledb/src/views/metadata.rs
  components/merkledb/src/views/tests.rs
  exonum/src/blockchain/schema.rs
  exonum/src/runtime/rust/mod.rs
  exonum/src/runtime/types.rs
  services/supervisor/tests/supervisor/main.rs
Labels: core, merkledb, update changelog

#1583 Resolve documentation todos [ECR-3275]
  exonum/src/explorer/mod.rs
  exonum/src/runtime/dispatcher/mod.rs
Labels: core, documentation

#1580 Update examples readmes according to 0.13
  examples/cryptocurrency-advanced/README.md
  examples/cryptocurrency-advanced/cryptocurrency_advanced.yaml
  examples/timestamping/README.md
  examples/timestamping/backend/Cargo.toml
  examples/timestamping/timestamping.yaml
  services/time/README.md
  services/time/examples/simple_service/main.rs
Labels: documentation
